config/routes.rb
require 'resque/server'

Rails.application.routes.draw do
  root "home#index"

  get '/me' => 'users#show'

  namespace :api do
    resources :clips
    resources :likes
    get 'channels/like' => 'channels#like'
    get 'channels/dislike' => 'channels#dislike'
    put 'channels/:id' => 'channels#update'
    delete 'destroy' => 'channels#destroy'
  end

  resources :channels

  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks' }
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup
  mount Resque::Server.new, at: "/resque"
end

app/models/clip.rb
class Clip < ActiveRecord::Base
  belongs_to :user
  belongs_to :channel
  mount_uploader :attachment, ClipUploader
  has_attached_file :local_mp3,
                    path: ":rails_root/public/system/:attachment/:id/:style/:basename.:extension",
                    url:  "/system/:attachment/:id/:style/:basename.:extension"

  has_attached_file :mp3,
    :storage => :s3,
    :s3_credentials => "#{Rails.root}/config/s3.yml",
    :path => "sounds/:id/:style.:extension",
    :url => ":s3_domain_url",
    :s3_host_name => "s3-website-us-west-1.amazonaws.com"
  process_in_background :mp3

  #before_validation :convert_to_mp3
  validates_attachment :mp3, content_type: { content_type: ["audio/wav", "mp3"] }
  after_save :queue_upload_to_s3

  def queue_upload_to_s3
    ClipUploadJob.perform_later id
  end

  def upload_to_s3
    self.mp3 = local_mp3.to_file if local_mp3? && local_mp3_updated_at_changed?
    save!
  end

  def reconvert_to_mp3
    wavfile = Tempfile.new(".wav")
    wavfile.binmode

    open(wav.url) do |f|
      wavfile << f.read
    end

    wavfile.close

    convert_tempfile(wavfile)
  end

  def convert_to_mp3
    tempfile = mp3.queued_for_write[:original]
    unless tempfile.nil?
      convert_tempfile(tempfile)
    end
  end

  def convert_tempfile(tempfile)
    dst = Tempfile.new(".mp3")

    cmd_args = [File.expand_path(tempfile.path), File.expand_path(dst.path)]
    system("lame", *cmd_args)

    dst.binmode
    io = StringIO.new(dst.read)
    dst.close
    self.mp3 = io
  end
end

app/controllers/api/clips_controller.rb
class Api::ClipsController < ApplicationController
  before_action :authenticate_user!

  def create
    @clip = Clip.create!(
      user: current_user,
      channel_id: params[:channel_id],
      name: params[:fname],
      local_mp3: params[:data]
    )

    render json: { clip_id: @clip.id, url: @clip.mp3.url }, status: 200
  end

  def destroy
    Clip.find(params[:id]).destroy!
    render json: { message: 'Success!' }, status: 200
  end

  def clip_params
    params.permit(:fname, :data)
  end
end

app/helpers/clips_helper.rb
module ClipsHelper
end

app/views/clips/index.html.erb
<% if !flash[:notice].blank? %>
  <div class="alert alert-info">
  <%= flash[:notice] %>
  </div>
<% end %>
<br />
<%= link_to "New clip", new_clip_path, class: "btn btn-primary" %>
<br />
<br />
<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Download Link</th>
      <th>&nbsp;</th>
    </tr>
  </thead>
  <tbody>
    <% @clips.each do |clip| %>
      <tr>
        <td><%= clip.name %></td>
        <td><%= link_to "Download clip", clip.attachment_url %></td>
        <td><%= button_to "Delete",  clip, method: :delete, class: "btn btn-danger", confirm: "Are you sure that you wish to delete #{clip.name}?" %></td>
      </tr>
    <% end %>
  </tbody>
</table>