config/routes.rb
require 'resque/server'

Rails.application.routes.draw do
  root "home#index"

  get '/me' => 'users#show'

  namespace :api do
    resources :clips
    resources :likes
    get 'channels/like' => 'channels#like'
    get 'channels/dislike' => 'channels#dislike'
    put 'channels/:id' => 'channels#update'
    delete 'destroy' => 'channels#destroy'
  end

  resources :channels

  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks' }
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup
  mount Resque::Server.new, at: "/resque"
end

app/views/partials/_edit_channel_modal.html.erb
<div id='edit-channel-modal' class='edit-clip-modal modal fade'>
  <div class='modal-dialog'>
    <div class='modal-content'>
      <%= form_for @channel, url: "/api/channels/#{ @channel.id }", action: :update, method: :put, remote: :true do %>
        <div class='modal-header'>
          Edit
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true"><%= fa_icon 'times' %></span></button>
        </div>
        <div class='modal-body'>
          <div class='mtl'>
            <input type='text' class='form-control full-width' name='channel[name]' value='<%= @channel.name %>' placeholder='name' />
          </div>
          <div class='mtl'>
            <a type="button" class="btn delete-btn" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">Cancel</span></a>
            <input type='submit' value='Save' class='btn btn-primary'/>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/partials/_edit_clip_modal.html.erb
<div id='edit-clip-modal' class='edit-clip-modal modal fade'>
  <div class='modal-dialog'>
    <div class='modal-content'>
      <div class='modal-header'>
        Edit Clip
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true"><%= fa_icon 'times' %></span></button>
      </div>
      <div class='modal-body'>
        <div class='mtl'>
          <input type='text' class='form-control full-width' name='clip[name]' value='' placeholder='name' />
        </div>
        <div class='mtl'>
          <a type="button" class="btn delete-btn" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">Cancel</span></a>
          <input type='submit' value='Save' class='btn btn-primary'/>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/partials/_login.html.erb
<div id="login-modal" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content text-center">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true"><%= fa_icon 'times' %></span></button>
        <h4 class="modal-title">Login</h4>
      </div>
      <div class="modal-body">
        <div class='bold mtl'>
          You must login to continue.
        </div>
        <div class='mtl text-left'>
          <%= render partial: 'partials/login_form', locals: { resource: User.new, resource_name: 'user' } %>
        </div>
        <div class='mtl text-left'>
          <button type="button" class="btn btn-default delete-btn btn-delete mrmd mtmd" data-dismiss="modal">
            <%= fa_icon 'remove' %>
            Cancel
          </button>
          <%= link_to "#{ fa_icon 'facebook' } Connect w/ Facebook".html_safe, omniauth_authorize_path('user', 'facebook'), { class: 'mtmd btn btn-primary login-btn mrmd'} %>
          <%= link_to "#{ fa_icon 'twitter' } Connect w/ Twitter".html_safe, omniauth_authorize_path('user', 'twitter'), { class: 'mtmd btn btn-primary login-btn'} %>
        </div>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/partials/_login_form.html.erb
<%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
    <div class="row mtmd field">
      <div class='col-xs-12 col-sm-3 text-left'>
        <%= f.label :email %>
      </div>
      <div class='col-xs-12 col-sm-9 text-left'>
        <%= f.email_field :email, { class: 'form-control', autofocus: true } %>
      </div>
    </div>

    <div class="row mtmd field">
      <div class='col-xs-12 col-sm-3 text-left'>
        <%= f.label :password %>
      </div>
      <div class='col-xs-12 col-sm-9 text-left'>
        <%= f.password_field :password, { class: 'form-control', autocomplete: "off" } %>
      </div>
    </div>

    <div class="row mvl actions">
      <div class='col-xs-12 text-left'>
        <%= f.submit "Log in", { class: 'btn btn-primary'} %>
      </div>
    </div>
  <% end %>

app/views/partials/_new_channel_modal.html.erb
<div id='new-channel-modal' class='new-channel-modal modal fade'>
  <%= form_tag'channels', method: :post, class: 'full-width' do %>
    <div class='modal-dialog col-xs-9 col-sm-4 col-md-2'>
      <div class='modal-content'>
        <div class='modal-header'>
          <%= fa_icon 'plus' %> Channel
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true"><%= fa_icon 'times' %></span></button>

        </div>
        <div class='modal-body'>
          <%= text_field_tag 'channel[name]', '', { placeholder: 'Channel name', class: 'mtmd form-control fade in '} %>
          <div class='mtl'>
            <a type="button" class="btn delete-btn" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">Cancel</span></a>
            <%= submit_tag 'Create', { class: 'btn mhmd btn-primary fade in' } %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/partials/_orig_synth.html.erb
<div class='col-xs-12 col-sm-mtl' id="p-wrapper">
  <ul id="piano">
    <% (2..5).each do |octave| %>
      <div class="octave">
        <li><div id="C<%= octave %>" class="anchor"></div></li>
        <li><div id="D<%= octave %>" class="anchor"></div><span id="Csharp<%= octave %>"></span></li>
        <li><div id="E<%= octave %>" class="anchor"></div><span id="Dsharp<%= octave %>"></span></li>
        <li><div id="F<%= octave %>" class="anchor"></div></li>
        <li><div id="G<%= octave %>" class="anchor"></div><span id="Fsharp<%= octave %>"></span></li>
        <li><div id="A<%= octave %>" class="anchor"></div><span id="Gsharp<%= octave %>"></span></li>
        <li><div id="B<%= octave %>" class="anchor"></div><span id="Asharp<%= octave %>"></span></li>
      </div>
    <% end %>
    <li><div id="C6" class="anchor"></div></li>
  </ul>
</div>
<div class='row center'>
  <div class='visible-xs col-xs-6 mtl'>
    <div class='row'>
      <div class='col-xs-12 block'>
        <h4 class='margin-auto inline text-center'>
          <%= fa_icon "gear" %> Synth Controls
        </h4>
      </div>
      <div class='col-xs-12 mtl'>
        <div class="onoffswitch margin-auto">
          <input data-toggle-class='hide' data-target='t2' class='toggle onoffswitch-checkbox' type="checkbox" name="syn-control-switch" id="syn-control-switch" checked>
          <label class="onoffswitch-label" for="syn-control-switch">
              <span class="onoffswitch-inner"></span>
              <span class="onoffswitch-switch"></span>
          </label>
        </div>
      </div>
    </div>
  </div>
  <div class='col-xs-12 col-sm-12 text-right inline-block mtl npl'>
    <span class='pull-left mrl'>
      Plug in a <b> MIDI controller </b> or use your <b> computer keyboard </b> to play.
    </span>
    <span class='mrl'>
      <label class='bold med'> R </label>: <%= fa_icon 'circle', class: 'red-text' %> Record / <%= fa_icon 'square' %> Stop
    </span>
    <span class='mrl'>
      <label class='bold med'> X </label>: <%= fa_icon 'arrow-up' %> octave
    </span>
    <span class='mrl'>
      <label class='bold med'> Z </label>: <%= fa_icon 'arrow-down' %> octave
    </span>
  </div>
</div>
<div class="recordings-container row mvmd">
</div>
<div class='fixed left bottom full-width t2 clearfix animate fade-animate synth-controls block center'>
  <div class='container'>
    <div class='col-xs-3 col-sm-1 col-md-1 no-padding'>
      <div class='col-xs-12'>
        <label class='animate full-width text-center'>
          Osc
        </label>
      </div>
      <div class='col-xs-12'>
        <select name="mode" id="synth-mode-selector" data-synth-field="synthMode" class="synth-field form-control" >
          <option name="envelope">envelope</option>
          <option name="lpf">LPF</option>
          <option name="pluck">pluck</option>
        </select>
      </div>
    </div>
    <div class='col-xs-3 col-sm-1 col-md-1 no-padding'>
      <div class='col-xs-12'>
        <label class='animate full-width text-center'>
          Wave
        </label>
      </div>
      <div class='col-xs-12'>
        <select name="wave" id="wave-selector" data-synth-field="wave" class="synth-field form-control" >
          <option name="sin">sin</option>
          <option name="saw">saw</option>
          <option name="tri">tri</option>
        </select>
      </div>
    </div>
    <div class='col-xs-3 col-sm-1 col-md-1'>
      <div class='col-xs-12 no-padding'>
        <label class='animate full-width text-center'>
          Attack
        </label>
      </div>
      <div class='col-xs-12 text-center no-padding'>
        <div type="number" id="synth-attack-input" data-synth-field="attack" name="synthAttack" class="knob synth-field synth-attack-input" data-default="0" data-type="seconds" data-min="0" data-max="1" data-step="0.05" placeholder="Attack 0-1s" value="1" ></div>
      </div>
    </div>
    <div class='col-xs-3 col-sm-1 col-md-1'>
      <div class='col-xs-12 no-padding'>
        <label class='animate full-width text-center'>
          Decay
        </label>
      </div>
      <div class='col-xs-12 text-center no-padding'>
        <div type="number" id="synth-decay-input" data-synth-field="decay" name="synthDecay" data-default="1" class="knob synth-field synth-Decay-input" data-type="seconds" placeholder="Decay 0-3s" data-step="0.25" data-min="0" data-max="3" value="1" ></div>
      </div>
    </div>
    <div class='col-xs-3 col-sm-1 col-md-1'>
      <div class='no-padding col-xs-12 text-center'>
        <label class='animate full-width text-center'>
          Release
        </label>
      </div>
      <div class='no-padding col-xs-12 text-center'>
        <div type="number" id="synth-release-input" data-synth-field="release" data-default="1" name="synthRelease" data-type="seconds" class="knob synth-field synth-release-input" data-min="0" data-max="10" data-step="1" placeholder="Release (0 - 10s)" value="1" ></div>
      </div>
    </div>
    <div class='col-xs-3 col-sm-1 col-md-1'>
      <div class='col-xs-12 text-center no-padding'>
        <label class='animate full-width text-center'>
          Reverb
        </label>
      </div>
      <div class='col-xs-12 text-center no-padding'>
        <div type="number" id="synth-reverb-input" data-synth-field="reverb" name="synthReverb" class="knob synth-field synth-reverb-input" data-min="0" data-max="1" placeholder="reverb 0-100%" data-step="0.1" value="0" ></div>
      </div>
    </div> 
    <div class='col-xs-3 col-sm-1 col-md-1'>
      <div class="col-xs-12 text-center no-padding">
        <label class='animate full-width text-center'>Vol</label>
      </div>
      <div class="col-xs-12 text-center no-padding">
        <div type="number" data-synth-field='mul' id="synth-volume-input" name="synthVolume" class="knob synth-field synth-volume-input" data-default="0.25" data-step="0.25" data-min="0.1" data-max="1" value="1" ></div>
      </div>
    </div>
    <div class='col-xs-3 col-sm-1 col-md-1'>
      <div class='row'>
        <div class='col-sm-12 text-center'>
          <label class='animate full-width text-center'>
            BPM
          </label>
        </div>
        <div class='col-sm-12 text-center no-padding'>
          <div type="number" id="synth-bpl-input" data-synth-field="bpm" name="synthBPL" class="knob synth-field synth-BPL-input" data-step="1" data-default="4" data-min="4" data-max="8" placeholder="Beats per record" value="4" ></div>
        </div>
      </div>
    </div>
    <div class='col-xs-3 col-sm-1 col-md-1 text-center'>
      <div class='row'>
        <div class='col-sm-12 text-center'>
          <label class='animate full-width'>Loop</label>
        </div>
        <div class='col-sm-12 text-center no-padding'>
          <a class='btn btn-large red-text med-font transition record-btn js-record-action' data-action='startRecording'>
            <%= fa_icon 'circle' %> Rec
          </a>
          <a class='btn btn-large hide med-font stop-btn js-record-action' data-action='stopRecording'>
            <%= fa_icon 'square' %> Stop
          </a>
        </div>
      </div>
    </div>
    <div class='col-xs-3 col-sm-1 col-md-1 text-center'>
      <label class='animate full-width text-center'>
        <span class='hidden-xs hidden-sm no-wrap'>
          Metronome
        </span>
        <span class='visible-sm visible-xs'>
          Metr.
        </span>
      </label>
      <div class=''>
        <div class="onoffswitch margin-auto">
          <input class='onoffswitch-checkbox js-record-action' data-action='toggleMetronome' type="checkbox" name="onoffswitch" id="myonoffswitch">
          <label class="animate onoffswitch-label" for="myonoffswitch">
              <span class="onoffswitch-inner"></span>
              <span class="onoffswitch-switch"></span>
          </label>
        </div>
      </div>
    </div>
    <div class='mtmd col-xs-3 col-sm-2 col-md-2 text-center'>
      <label class='animate recording-status mtl red-text full-width text-center'>
      </label>
    </div>
  </div>
</div>
<%= render partial: "partials/templates/record_row" %>

app/views/partials/_synth.html.erb
<div id="synthbox">
    <div class="knobContainer" id="fControl" style="left: 10px; top: 10px;">
        <input class="knob" data-width=100 data-angleOffset=-125 data-angleArc=250 data-fgColor="#66EE66" value="35">
        <div class="knobLabel">frequency</div>
    </div>
</div>
<div id="keybox" touch-action="none">
    <div id="blackkeys">
        <span id="k61" class="black key"></span><span id="k63" class="black key"></span><span class="spacer"></span><span id="k66" class="black key"></span><span id="k68" class="black key"></span><span id="k70" class="black key"></span><span class="spacer"></span><span id="k73" class="black key"></span><span id="k75" class="black key"></span><span class="spacer"></span><span id="k78" class="black key"></span><span id="k80" class="black key"></span><span id="k82" class="black key"></span>
    </div>
    <span id="k60" class="white key"></span><span id="k62" class="white key"></span><span id="k64" class="white key"></span><span id="k65" class="white key"></span><span id="k67" class="white key"></span><span id="k69" class="white key"></span><span id="k71" class="white key"></span><span id="k72" class="white key"></span><span id="k74" class="white key"></span><span id="k76" class="white key"></span><span id="k77" class="white key"></span><span id="k79" class="white key"></span><span id="k81" class="white key"></span><span id="k83" class="white key"></span>
</div>