config/routes.rb
require 'resque/server'

Rails.application.routes.draw do
  root "home#index"

  get '/me' => 'users#show'

  namespace :api do
    resources :clips
    resources :likes
    get 'channels/like' => 'channels#like'
    get 'channels/dislike' => 'channels#dislike'
    put 'channels/:id' => 'channels#update'
    delete 'destroy' => 'channels#destroy'
  end

  resources :channels

  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks' }
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup
  mount Resque::Server.new, at: "/resque"
end

app/models/user.rb
class User < ActiveRecord::Base
  require "open-uri"
  extend FriendlyId

  has_many :channels, dependent: :destroy
  has_many :clips, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :connections, dependent: :destroy

  friendly_id :name, use: :slugged
  TEMP_EMAIL_PREFIX = 'change@me'
  TEMP_EMAIL_REGEX = /\Achange@me/

  # Include default devise modules. Others available are:
  # :lockable, :timeoutable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable, :omniauthable, omniauth_providers: [ :facebook, :twitter ]

  validates_format_of :email, :without => TEMP_EMAIL_REGEX, on: :update
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

  def full_name
    name || "Guest #{ rand(1000) }"
  end

  def liked(channel)
    likes.where(likable_id: channel.id).exists?
  end

  def download_profile_pic(url)
    begin
      io = open(URI.parse(url))
      test = url.split('/').last.blank?
      self.avatar = test ? nil : io  
    rescue Exception => e
      Rails.logger.error e.message
      self.avatar = nil
    end
  end

  def self.find_for_oauth(auth, signed_in_resource = nil)

    # Get the identity and user if they exist
    identity = Identity.find_for_oauth(auth)

    user = signed_in_resource ? signed_in_resource : identity.user

    # Create the user if needed
    if user.nil?

      email = auth.info.email
      user = User.where(:email => email).first if email

      # Create the user if it's a new registration
      if user.nil?
        user = User.new(
          name: auth.extra.raw_info.name,
          #username: auth.info.nickname || auth.uid,
          email: email ? email : "#{TEMP_EMAIL_PREFIX}-#{auth.uid}-#{auth.provider}.com",
          password: Devise.friendly_token[0,20],
        )
        user.download_profile_pic(auth.info.image)
        user.save!
      end
    end

    if identity.user != user
      identity.user = user
      identity.save!
    end
    user
  end

  def email_verified?
    self.email && self.email !~ TEMP_EMAIL_REGEX
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:destroy, :finish_signup]
  before_action :authenticate_user!, only: [ :destroy, :update, :edit ]
  # GET /users/:id.:format
  def show
    @user = current_user
    @channel = Channel.new
  end

  # GET /users/:id/edit
  def edit
    # authorize! :update, @user
  end

  # PATCH/PUT /users/:id.:format
  def update
    # authorize! :update, @user
    respond_to do |format|
      if @user.update(user_params)
        sign_in(@user == current_user ? @user : current_user, :bypass => true)
        format.html { redirect_to @user, notice: 'Your profile was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET/PATCH /users/:id/finish_signup
  def finish_signup
    # authorize! :update, @user 
    if request.patch? && params[:user] #&& params[:user][:email]
      if @user.update(user_params)
        sign_in(@user, :bypass => true)
        redirect_to '/', notice: 'Your profile was successfully updated.'
      else
        @show_errors = true
      end
    end
  end

  # DELETE /users/:id.:format
  def destroy
    # authorize! :delete, @user
    @user.destroy
    respond_to do |format|
      format.html { redirect_to root_url }
      format.json { head :no_content }
    end
  end
  
  private
    def set_user
      @user = User.find_by_slug(params[:id]) || User.friendly_id.find(params[:id]) || User.find(params[:id])
    end

    def user_params
      accessible = [ :name, :email ] # extend with your own params
      accessible << [ :password, :password_confirmation ] unless params[:user][:password].blank?
      params.require(:user).permit(accessible)
    end
end

app/views/users/finish_signup.html.erb
<div id="add-email" class="mtxl col-xs-12 col-sm-12 container">
  <div class='row'>
    <div class='col-xs-12'>
      <h3>Add Email</h3>
    </div>
  </div>
  <%= form_for(current_user, :as => 'user', :url => finish_signup_path(current_user), :html => { role: 'form'}) do |f| %>
    <% if @show_errors && current_user.errors.any? %>
      <div id="error_explanation">
        <% current_user.errors.full_messages.each do |msg| %>
          <%= msg %><br>
        <% end %>
      </div>
    <% end %>
    <div class='row mtl'>
      <div class="form-group">
        <div class='col-xs-12 col-sm-2'>
          <%= f.label :email %>
        </div>
        <div class="col-xs-12 col-sm-8 controls">
          <%= f.text_field :email, :autofocus => true, :value => '', class: 'form-control input-lg', placeholder: 'Example: email@me.com' %>
          <p class="mtl help-block">Please confirm your email address, so I can send you pics of my abs. No spam, of course. </p>
        </div>
      </div>
    </div>
    <div class="row mtl actions">
      <div class='col-xs-12'>
        <%= f.submit 'Continue', :class => 'btn btn-primary' %>
      </div>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<div class='container'>
  <div class='row mvl'>
    <div class='col-xs-12 mtl'>
      <h3>
        <%= fa_icon 'th-large' %> Dashboard
      </h3>
    </div>
  </div>
  <div class='row mtl fade in'>
    <div class='col-xs-12 col-md-6'>
      <h3 class='border-bottom pbl'>
        Channels
      </h3>
      <div class='row mtl'>
        <div class='col-xs-12'>
          <div class='row'>
            <ul>
              <li class='mvl col-xs-3 col-md-4 inline-block clearfix'>
                <a class='full-width channel-container transition border btn btn-primary add-channel-btn green-bg' id='show-create-channel-form'>
                  <div class='center bold'>
                    <%= fa_icon 'plus' %> Channel
                  </div>
                </a>
              </li>
              <% if @user.channels.length > 0 %>
                <% @user.channels.each do |channel| %>
                  <li class='mvl col-xs-3 col-md-4 inline-block clearfix'>
                    <div class='pbmd ptmd fade-animate'>
                     
                      <div class='transition channel-container border'>
                        <div class='center'>
                          <%= link_to channel.name, channel_path(channel), { class: 'white-text bold transition' } %>
                          <br />
                          <div class='pull-left inline big'>
                             <%= link_to fa_icon('headphones').html_safe, channel_path(channel), { class: 'transition white-text bold' } %>
                            <%= link_to  fa_icon('trash').html_safe, { action: :destroy, controller: 'channels', id: channel.id }, method: :delete, data: { confirm: 'Are you sure you want to delete this?' }, class: 'transition white-text bold big'  %>
                          </div>
                          <div class='mvsm pull-right inline small'>
                            <%= fa_icon 'thumbs-up', { class: 'bold' } %> <%= channel.likes.count %>
                          </div>
                        </div>
                      </div>
                    </div>
                  </li>
                <% end %>
              <% else %>
                <li>
                  <div class='col-xs-12'>
                    No channels to show.
                  </div>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>
    <div class='col-xs-12 col-md-6'>
      <h3 class='border-bottom pbl'>
        <%= fa_icon 'file' %> Files
      </h3>
      <div class='row mtl'>
        <div class='col-xs-12'>
          <div class='row'>
            <% if @user.clips.length != 0 %>
              <ul>
                <% @user.clips.each do |clip| %>
                 <li class='mvl col-xs-3 col-md-4 inline-block clearfix'>
                    <div class='pbmd ptmd fade-animate'>
                      <div class='transition clip-container channel-container border'>
                        <div class='center'>
                          <span class='bold full-width'>
                            <%= clip.name %>
                            <br />
                          </span>
                          <span class='big white-text'>
                            <%= link_to fa_icon('save').html_safe, clip.mp3.url, { target: '_blank', class: 'transition'} %>
                            <%= link_to fa_icon('trash').html_safe, { action: :destroy, controller: "api/clips", id: clip.id }, method: :delete, data: { remote: true, confirm: 'Are you sure you want to delete this?' }, class: 'transition' %>
                            <div>
                        </div>
                      </div>
                    </div>
                  </li>
                <% end %>
              </ul>
            <% else %>
              <div class='col-xs-12'>
                No files to show.
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<%= render partial: 'partials/new_channel_modal' %>